### ISSUE TITLE
Support for PayPal Commerce Platform (PPCP)?

### ISSUE THREAD

**Issue by plorenz-etes** [leadingsystems/contao-merconis#121]
One of my customers uses Merconis with PayPal Plus enabled. He recently received an email from PayPal advertising the PayPal Commerce Platform (PPCP) which he can activate in his PayPal settings. More information can be found here: https://developer.paypal.com/docs/multiparty/

Will this work with the existing PayPal payment code in Merconis without needing to adjust any settings? I was in contact with a PayPal employee but he didn't really understand my issue and only told me that integration was easy.

Sorry for asking this here, but I can't register on your forums due to a "suspicious email address" error.

**Comment by chiron501** [comment]
Since Merconis 4.0.18 and Merconis 5.0, PayPal Checkout has been added as an additional payment option.
