### ISSUE TITLE
Google Tag Manager integration

### ISSUE THREAD

**Issue by landzone21** [leadingsystems/contao-merconis#400]
We would like to integrate Google Tag Manager into MERCONIS.
We need a datalayer for the steps product viewed, product added to cart, checkout started, purchase completion, etc.
For example, we would use the tracking code for the completion of the purchase in the form

`<script>
window.dataLayer.push({ ecommerce: null }); // Clear the previous ecommerce object.
window.dataLayer.push({
    event: "purchase", // or "add_to_cart" ...
    ecommerce: {
        transaction_id: "T_12345", // ordernumber
        value: 72.05,
        currency: "EUR",
        items: [{ 
            item_id: "SKU_12345",
            item_name: "Stan and Friends Tee",
            price: 10.01,
            quantity: 3
        }]
    }
});
</script>`
...
into the template template_afterCheckout_default.html5. Is this the right way? Are the variables still available afterCheckout?
What are the corresponding templates for the individual steps? Cookie management is carried out via Oveleon's cookie bar.

**Comment by chiron501** [comment]
The template 'template_afterCheckout_default.html5' is the right template to deliver data to external systems after order completion. You have access to all relevant order data via the arrOrder[...] array.
As you can see at the beginning of the template, data for GTM based on HTML code is made available here. This is just another method.
However, you can also use the arrOrder[...] array to fill the Javascript object for the dataLayer push.

For further questions please use our forum:
https://www.leadingsystems.de/contao-forum-support-shop/

**Comment by landzone21** [comment]
Thanks a lot, it's very helpful. Is this code for the GTM also available in other templates, i.e. in the  steps (addedToCart etc.)? 
I couldn't find anything about it.
Unfortunately, your forum has obviously been hacked.

**Comment by chiron501** [comment]
The code is not available in other templates. However, you have the option of using customized store templates to place the code where you need it.

Product detail view:
Template: template_productDetails_01.html5

Shopping cart:
Template: Necessary templates start with template_cart_big...

Chechout steps:

1. order summary:
Template: template_orderReview_default.html5

2. order completion:
Template: Necessary templates start with template_afterCheckout...

To add to the shopping cart, you must either place a trigger on the “shopping cart button” or use our hook “addToCart” (https://www.merconis.com/techsupport/contao-handbuch-onlineshop-v5/features-fuer-entwickler/hooks/addtocart.html) in your extension.
