### ISSUE TITLE
Delete deviant shipping address when checkbox is unchecked

### ISSUE THREAD

**Issue by vstuber** [leadingsystems/contao-merconis#49]
There's a checkbox in the user date form which is used to show or hide the input fields for the deviant shipping address (useDeviantShippingAddress). If this checkbox is checked and the input fields for the deviant shipping address are displayed, an address can be entered and is sent with the form on submit. If the checkbox is unchecked before sending the form, the user can't see the input fields but they are still being submitted. That results in the deviant shipping address being used in the DHL export which is obviously a problem and could possibly lead to shipment to a wrong address.

We need to make sure that unchecking the checkbox "useDeviantShippingAddress" instantly deletes the input fields for the deviant shipping address so that those values can not be submitted.

**Comment by chiron501** [comment]
#188
