### ISSUE TITLE
Sofortüberweisung SDK per Composer einbinden

### ISSUE THREAD

**Issue by vstuber** [leadingsystems/contao-merconis#6]
**Abhängigkeit von der Sofortüberweisung SDK**

Die SDK von Sofortüberweisung wird derzeit im `vendor` Verzeichnis mitgeliefert. Hier wäre es empfehlenswert auch über Composer die aktuelle Version zu laden. Die API hat sich hier wohl etwas geändert. https://github.com/sofort/sofortlib-php

Im Moment funktioniert es auch noch, die SDK von Sofortüberweisung wie bisher direkt mit dem Merconis Core auszuliefern. Deshalb gehen wir diesen grundsätzlich sinnvollen/nötigen Umbau erst an, wenn wir etwas Luft haben, uns in Ruhe mit den API-Änderungen von Sofortüberweisung auseinanderzusetzen.

**Comment by chiron501** [comment]
Sofortüberweisung was taken over by Klarna and the API was changed.
